services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/client
      - /client/node_modules
      - /client/.next
    ports:
      - "3001:3000"
    command: yarn dev --hostname 0.0.0.0
